name: "04-rabbitmq"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "5672:5672"   # Standard RabbitMQ Port
      - "15672:15672" # Management UI Port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
  producer:
    build:
      context: ./producer
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
    depends_on:
      - rabbitmq
    volumes:
      - ./producer/producer.py:/app/producer.py # Mounting the producer script

  consumer:
    build:
      context: ./consumer
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - SEVERITIES=info, warning
    depends_on:
      - rabbitmq
    volumes:
      - ./consumer/consumer.py:/app/consumer.py # Mounting the consumer script
    # deploy:
    #   replicas: 2
  consumer-error:
    build:
      context: ./consumer
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - SEVERITIES=error
    depends_on:
      - rabbitmq
    volumes:
      - ./consumer/consumer.py:/app/consumer.py # Mounting the consumer script

  # consumer-debug:
  #   build:
  #     context: ./consumer
  #   environment:
  #     - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
  #     - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
  #     - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
  #     - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
  #     - SEVERITIES=info, debug
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - ./consumer/consumer.py:/app/consumer.py # Mounting the consumer script

volumes:
  rabbitmq_data: