name: "01-celery"
services:
  message-broker:
    image: rabbitmq:3.13-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    restart: always
    ports:
      - "5672:5672"   # Standard RabbitMQ Port
      - "15672:15672" # Management UI Port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  result-backend:
    image: redis:8-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    restart: always
    environment:
      - RI_REDIS_HOST=${REDIS_CONTAINER_NAME}
      - RI_REDIS_PORT=6379
      - RI_REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - result-backend
    volumes:
      - redisinsight_data:/data
    
  worker:
    build:
      context: ../00_image_base/python3-celery
    image: alpine-python3-celery:latest
    pull_policy: never
    command: ["celery", "-A", "worker", "worker", "--loglevel=INFO", "--concurrency=4", "--prefetch-multiplier=1"]
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - REDIS_HOST=${REDIS_CONTAINER_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - message-broker
      - result-backend
    volumes:
      - ./worker/worker.py:/app/worker.py
    deploy:
      replicas: ${WORKER_REPLICAS}
    
  consumer:
    image: alpine-python3-celery:latest
    pull_policy: never
    command: ["python", "/app/src/consumer.py"]
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - REDIS_HOST=${REDIS_CONTAINER_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    depends_on:
      - worker
    volumes:
      - ./consumer/consumer.py:/app/src/consumer.py
      - ./worker/worker.py:/app/src/worker.py
    deploy:
      replicas: ${CONSUMER_REPLICAS}

volumes:
  rabbitmq_data:
  redis_data:
  redisinsight_data: