name: "07-rabbitmq"
services:
  rabbitmq-node1:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq-node1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    hostname: rabbitmq-node1
    networks:
      - rabbits
    ports:
      - "15672:15672"
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster.conf:/etc/rabbitmq/conf.d/cluster.conf

  rabbitmq-node2:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq-node2
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    hostname: rabbitmq-node2
    networks:
      - rabbits
    ports:
      - "15673:15672"
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster.conf:/etc/rabbitmq/conf.d/cluster.conf

  rabbitmq-node3:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq-node3
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    hostname: rabbitmq-node3
    networks:
      - rabbits
    ports:
      - "15674:15672"
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster.conf:/etc/rabbitmq/conf.d/cluster.conf

  producer:
    build:
      context: ../00_image_base/python3-pika
    image: alpine-python3-pika:latest
    pull_policy: never
    command: ["python", "/app/producer.py"]
    environment:
      - RABBITMQ_HOSTS=${RABBITMQ_HOSTS}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./producer/producer.py:/app/producer.py
    networks:
      - rabbits

networks:
  rabbits:
    driver: bridge